// Copyright 2023 Sharapov Georgiy
#ifndef TASKS_TASK_3_SHARAPOV_G_CONV_HULL_CONN_COMP_CONNECTED_COMPONENT_H_
#define TASKS_TASK_3_SHARAPOV_G_CONV_HULL_CONN_COMP_CONNECTED_COMPONENT_H_

int* marking(int* image, size_t n, size_t k);

#endif  // TASKS_TASK_3_SHARAPOV_G_CONV_HULL_CONN_COMP_CONNECTED_COMPONENT_H_
