// Copyright 2023 Kuznetsov Artem
#ifndef TASKS_TASK_3_KUZNETSOV_A_CONTRAST_ENHANCEMENT_CONTRAST_ENHANCEMENT_H_
#define TASKS_TASK_3_KUZNETSOV_A_CONTRAST_ENHANCEMENT_CONTRAST_ENHANCEMENT_H_

#include <mpi.h>

int sum(int a, int b);

#endif  // TASKS_TASK_3_KUZNETSOV_A_CONTRAST_ENHANCEMENT_CONTRAST_ENHANCEMENT_H_
