// Copyright 2023 Musaev Ilgar
#ifndef TASKS_TASK_2_MUSAEV_I_READERS_WRITERS_READERS_WRITERS_H_
#define TASKS_TASK_2_MUSAEV_I_READERS_WRITERS_READERS_WRITERS_H_

int startTask(int writersCount);

#endif  // TASKS_TASK_2_MUSAEV_I_READERS_WRITERS_READERS_WRITERS_H_
